require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false
production = ENV["PRODUCTION"] == "1"
target 'RN_Boilerplate_TS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks! :linkage => :static
  config = use_native_modules!

  flags = get_default_flags()
  use_react_native!(
    :path => config[:reactNativePath],
    :production => production,
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'RN_Boilerplate_TSTests' do
    inherit! :search_paths
    # Pods for testing
  end

    
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
    react_native_post_install(installer)
      __apply_Xcode_12_5_M1_post_install_workaround(installer)
    end
end
